.\" $Id: fimgs.man 220 2009-02-25 02:47:27Z dezperado $
.TH fimgs 1 "(c) 2007-2009 Michele Martone"
.SH NAME
fimgs - poor man's [http://]PostScript/pdf/dvi/cbr/rar/cbz/zip viewer for the linux
framebuffer console
.SH SYNOPSIS
.B fimgs [ options ] file
.SH DESCRIPTION
.B fimgs  
is a simple wrapper script which takes a PostScript or pdf
or .cbr or .rar or .cbz or .zip or .dvi
or any of the above
prefixed with http:// 
as input, renders the pages using ghostscript into a
temporarely directory and finally calls fbi to display them.
In case of compressed archives (in zip or rar formats), the images 
are decompressed into a directory and displayed.
In this latter case, only images contained in the archive will be displayed
(no nested archives or pdf's or ps's or dvi's).
.SH OPTIONS
.\" fimgs understands all fim options (they are passed through).
.B fimgs
still does not understand all of fim's options (they are not passed through).
so please use 
.B fimgs -h
to get help on its options.

.\" Additionally you can specify -l, -xl or -xxl to get the pages
.\" rendered with 100, 120 or 150 dpi (default is 75).

You can
use option -p <password> if your PDF file requires password.
.SH SEE ALSO
fim(1), gs(1), fbi(1), fbgs(1), bash(1)
.SH AUTHOR
Michele Martone <dezperado _ GUESS _ autistici.org>. 
